# Generated by Django 5.2.6 on 2025-09-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('parent_name', models.CharField(max_length=255)),
                ('parent_phone_number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('unenrollment_date', models.DateField(auto_now=True, null=True)),
            ],
        ),
    ]
