<<<<<<< HEAD
# Generated by Django 5.2.6 on 2025-09-07 09:15
=======
# Generated by Django 5.2.6 on 2025-09-10 09:42
>>>>>>> muzaffar

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('full_name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('parent_name', models.CharField(max_length=255)),
                ('parent_phone_number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('unenrollment_date', models.DateField(auto_now=True, null=True)),
=======
                ('name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('parent_name', models.CharField(max_length=255)),
                ('parent_phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('unenrollment_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('left', 'Left'), ('graduated', 'Graduated')], default='active', max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
>>>>>>> muzaffar
            ],
        ),
    ]
