<<<<<<< HEAD
# Generated by Django 5.2.6 on 2025-09-07 09:15
=======
# Generated by Django 5.2.6 on 2025-09-10 09:42
>>>>>>> muzaffar

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('child', '0001_initial'),
<<<<<<< HEAD
        ('groups', '0001_initial'),
=======
        ('group', '0001_initial'),
>>>>>>> muzaffar
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='group',
<<<<<<< HEAD
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group'),
=======
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.group'),
>>>>>>> muzaffar
        ),
    ]
