# Generated by Django 5.2.6 on 2025-09-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='balance',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
